title: "TGM Guide"
baseurl: "/tgm-tips-rebuilt"
url: "https://octopuserectus.github.io"

collections:
  tips:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_tips"
    values:
      layout: "tip"

include:
  - "en-vd"
  - "en-ai"
  - "jp"